Iter5
amidvn/go-metrics pull request #5
Opened 2023-05-09 22:35 UTC by amidvn

2023-05-10 14:47 UTC, maxlyaptsev requested changes

2023-05-10 14:47 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +		if metricsType == "counter" {
при большом количестве условий (больше одного-двух) лучше использовать switch - читается намного лече, выглядит все аккуратней

2023-05-10 14:47 UTC, maxlyaptsev commented on cmd/agent/main.go
> +	if envRunAddr := os.Getenv("ADDRESS"); envRunAddr != "" {
если использовать сторонние пакеты для flag/env можно существенно сократить и упростить код

2023-05-14 18:03 UTC, amidvn commented
Внес изменения по комментариям:
- убрал рефлексию
- сократил использование else в условиях, заменил в одном месте на switch
- решил оставить стандартные flag\os библиотеки: при использовании библиотеки caarlos0/env тесты почему-то не проходили, а протестировать использование переменных окружения на личном ноутбуке не удается (VScode их не видит)

2023-05-14 21:25 UTC, maxlyaptsev approved these changes

2023-05-14 21:25 UTC, maxlyaptsev commented on cmd/agent/main.go
> +var cfg Config
лучше избавиться от локальных переменных и использовать локальные

2023-05-18 11:29 UTC, merged